---
apiVersion: appstudio.redhat.com/v1alpha1
kind: InternalRequest
metadata:
  name: myrequest
  namespace: default
spec:
  pipeline:
    pipelineRef:
      resolver: cluster
      params:
        - name: name
          value: sample
