---
name: Go Test on Pull Requests
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**.go'
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
jobs:
  gosec:
    name: Check GO security
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Gosec Security Scanner
        uses: securego/gosec@14f493ab92f212e1f3d69aeaa561989e5baf9d6f # master
        with:
          args: -exclude-generated ./...
        env:
          GOROOT: ""
