---
name: Go Test on Pull Requests
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**.go'
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
jobs:
  gosec:
    name: Check GO security
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Gosec Security Scanner
        uses: securego/gosec@cbef395cb1e2e3a35f6223f5b97f1657f7144797 # master
        with:
          args: -exclude-generated ./...
        env:
          GOROOT: ""
